stages:
  video-extraction:
    cmd : python src/video-extraction.py
    deps:
    - src/video-extraction.py
    outs:
    - dataset_preprocessed

  fileorganizer:
    cmd : python src/dileorganizer.py
    deps: 
    - 
    
